Server:
  Port: 5005
  RunMode: debug
Logger:
  FilePath: ../logs/logs.log
  Encoding: json
  level: debug
cors:
  allowOrigins: *
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbname: car_sale_db
  sslmode: false
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  minIdleConnections: 100
  poolSize: 5000
  poolTimeout: 240